stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip --version
  - pip install --upgrade pip
  - pip install zipp
  - pip install lark

build:
  stage: build
  image: python:3.10
  script:
    - pip install build  # use 'build' to create a wheel
    - python -m build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  image: python:3.10
  dependencies:
    - build
  script:
    - pip install dist/*.whl
    - pytest
